#+TITLE: gnus-mylist

* Gnus-Mylist
Track (my) Gnus articles and emails - not all of them, just what matters to me,
using a list and the convenience of a helm interface.

The gnus-mylist works with your Gnus, it can not replace it. Neither can it damage
or hurt your Gnus. Your Gnus is safe. It just works in the background, unimpending,
efficiently and quietly, keeping track of the articles read with gnus. When an
article is read, it adds a quick note to mylist. It removes notes of deleted
articles or the ones expunged by gnus.

Providing a good level of Gnus-Org integration. It will
enhance your Gnus experience. Simply, that's all.

This simplicity allows the user to add and remove articles to
gnus-mylist, stress free.

Viewing gnus-mylist with the powerful helm interface brings great search
capabilities and all the other helm goodness.
Gnus-mylist has been built around helm.

Gnus is not limited to email, that is why gnus uses the term "articles". Gnus-mylist
follows the Gnus general philosophy, it also uses the term "articles". Most testing
has been done on email (and IMAP in particular) and RSS.

This work is a fork of =unhammer='s [[https://github.com/unhammer/gnus-recent/blob/master/gnus-recent.el][gnus-recent]]. Some ideas for integration with
other emacs features are from =ericabramamsens='s [[http://elpa.gnu.org/packages/gnorb.html][gnorb]] packages.

This is still work in progress. But safe to use.

** Deleted

This is "my list", so I can keep only the articles that are important to me. The
rest I can simply remove from mylist, without affecting Gnus. If an article is
removed, by accident or I want it back for whatever reason, no problem. All I have
to do is view the article in gnus, and it is back on the list !

Gnus-mylist is similar to the Gnus registry, but whereas the
registry tries to catch everything, gnus-mylist is light-weight.
It doesn't try to keep everything. Only the articles "I have"
read. Its job is much simpler. "My read" articles are the only
really important "to me" articles, isn't is so ?

Gnus mylist works in the background silently, keeping track of
the articles read with gnus. When an article is read, it adds it
to mylist. Simply, that's all. It removes deleted articles or
the ones expunged by gnus.


** Prerequisites

   The following packages are required, for =gnus-mylist=:
   - =bbdb= and =bbdb-mua=
   - =gnus=
   - =org-gnus= or the newer =ol-gnus=.
   - =helm-lib=
   - =s=
   - =rfc2047=

** Installation

   Installation is still a manual process. Place the files in a directory, add it
   the load path. Load the library or using require:
   :
   : (require 'helm-gnus-mylist) 
   : (require 'gnus-mylist-org) 

   Now your gnus-mylist is waiting to start tracking your Gnus.

** Usage

   After loading the =gnus-mylist= library, start your =gnus= and read a few
   articles (emails).  To view the list of the emails and articles just read, type
   the command =gnus-mylist-helm=.

   For quick access assign to a global key, such as:
   :
   : (global-set-key (kbd "C-c m") #'helm-gnus-mylist)
   :
   Or add an option to your favorite hydra.


   The =C-c t= key binding is activated, by default with different actions
   depending on the mode:
   - in =org-mode=, it lists all the =gnus:= type links under the current org subtree.
   - in =summary= or =article-mode=, i.e. while reading, lets you take a quick note
     using the org-capture system. Perhaps, directly creating a REPLY to-do heading
     with your notes. 

** 
