#+TITLE: gnus-mylist

* Gnus-Mylist
Track (my) Gnus articles and emails - not all of them, just what matters to me,
using a list and the convenience of a helm interface.

Whether email or news, some people believe Gnus is a great article reader. They
probably like the Gnus philosophy, the way it "gets out of your way", its
flexibility and more.

The gnus-mylist works with your Gnus, it can not replace it. Neither can it damage
or hurt your Gnus. Your Gnus is safe. It just works on the side, unimpending,
efficiently and quietly. Providing a good level of Gnus-Org integration. It will
enhance your Gnus experience.

This work was inspired by unhammer's [[https://github.com/unhammer/gnus-recent/blob/master/gnus-recent.el][gnus-recent]] and by ericabramamsens's [[http://elpa.gnu.org/packages/gnorb.html][gnorb]]
packages.

This is still work in progress. Not ready yet for prime time. But it safe.

** Prerequisites

   The following packages are required, for =gnus-mylist=:
   - =bbdb= and =bbdb-mua=
   - =gnus=
   - =org-gnus= or the newer =ol-gnus=.
   - =helm-lib=
   - =s=
   - =rfc2047=

** Installation

   Installation is still a manual process. Place the files in a directory
   (preferably of their own). Before you start your Gnus, in your Emacs enter the
   command =M-x load-file= to load the file =load-all.el=. Now your gnus-mylist is
   waiting to start tracking your Gnus.

** Usage

   Start your =gnus= and read few articles or emails. To view the list of the emails
   and articles just read, type the command:
   : M-x gnus-mylist-helm

   The =C-c t= key binding is activated, by default with different actions
   depending on the mode:
   - in =org-mode=, it lists all the =gnus:= type links under the current org subtree.
   - in =summary= or =article-mode=, i.e. while reading, lets you take a quick note
     using the org-capture system. Perhaps, directly creating a REPLY to-do heading
     with your notes. 
